apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:eks:us-east-1:455225680207:nodegroup/hello-web-eks/default-20251015203719754200000005/1eccf4cb-b62f-bc74-693d-3fafb6024a05
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::455225680207:root
      username: admin
      groups:
        - system:masters
